apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: habit-tracker
  labels:
    app: backend
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGO_URI: "mongodb://mongodb-service:27017/habits-app" 