apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: habit-tracker
  labels:
    app: backend
type: Opaque
data:
  # Change this in production! This is base64 encoded "your_super_secret_jwt_key_change_in_production"
  JWT_SECRET: eW91cl9zdXBlcl9zZWNyZXRfand0X2tleV9jaGFuZ2VfaW5fcHJvZHVjdGlvbg== 