apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: habit-tracker
  labels:
    app: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: backend
  type: ClusterIP 