apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: habit-tracker
  labels:
    type: local
    app: mongodb
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: habit-tracker
  labels:
    app: mongodb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 